### ISSUE TITLE
BarcodeImage(String[] str_data) needs check for NULL values

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/BarcodeReader#11]
REGARDING:
BarcodeImage(String[] str_data)  constructor

Needs to check for NULL values.  Maybe should refactor to have a private utility method checkSize(String[] data) as recommended, but not required, per the spec.  

If anyone else sees other issues with this method.  Please post here.

**Comment by mdoussias** [comment]
I want to see if there are issues with the interaction of the other classes before I refactor.
As long as null values aren't entered this should work, for now.  

If anyone needs this fixed right away, let me know.

**Comment by mdoussias** [comment]
- [ ] Quality check that values will not go out of range for col

- [ ] Quality check that values will not go out of range for row

- [ ] Quality check that null values are considered in string array[]

**Comment by mdoussias** [comment]
I fixed this class up a little more to to have it decrement on the outer for loop because I think that will meet the specs requirements for having the image start in the lower left hand corner....
... However, this will be easier to test and fix once the other classes are completed because I'll be able to see if an image is copying right.  Will leave for now, but note this will still need fixed to account for null values and to verify in higher classes.

**Comment by mdoussias** [comment]
For anyone who reads this, on the Default constructor for the BarcodeImage class I'm wondering if I should simplify it.

I think when I made this I made it too complicated because all boolean values initialize to false.

**So a GOOD default constructor should have ONLY this code ?:**
 private boolean[][] image_data = new boolean[MAX_HEIGHT][MAX_WIDTH];   
 BarcodeImage(){}

**and below is BAD default constructor because all values in the array is already initialized to false?**

private boolean[][] image_data = new boolean[MAX_HEIGHT][MAX_WIDTH];

   BarcodeImage()
   {
      // Initialize 2D array to have all white values, i.e. false values
      for (int row = 0; row < MAX_HEIGHT; row++)
      {
         for (int col = 0; col < MAX_WIDTH; col++)
         {
            image_data[row][col] = false;
         }
      }
   }

**or am I wrong?**

**Comment by hmason55** [comment]
@mdoussias Hey, sorry for the late response. You are correct, in Java you only need this code to initialize a boolean array to all false values:
`image_data = new boolean[MAX_HEIGHT][MAX_WIDTH];`

However, if you wanted them to all be true then you would need that extra step you listed or use the Arrays library like this:
`//Initalizes to default which is false.`
`image_data = new boolean[MAX_HEIGHT][MAX_WIDTH]; `

`// Sets all values to true.`
`Arrays.fill(image_data, Boolean.TRUE); `

Here's some other default values for arrays if you are interested:
[Default array values in Java](https://www.geeksforgeeks.org/default-array-values-in-java/)
