### ISSUE TITLE
Clonable interface missing from BarcodeImages

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/BarcodeReader#13]
Clonable interface missing from BarcodeImages
Plans to complete Saturday morning or before

**Comment by mdoussias** [comment]
Maco will tackle this tomorrow morning (Saturday 03-23-18)
However, not sure if important to other's in the meantime, so leaving unassigned if somebody needs to work on it tonight and wants to assign themselves

**Comment by mdoussias** [comment]
This was added. Still needs testing. 

- [ ] Confirmed and tested in higher classes.

**Comment by p12345vls** [comment]
The instructions require us to catch a  CloneNotSupportedException in the scan(BarcodeImage bc). That means that the method in the BarCodeImage Class needs to throw the exception. Either the scan() should catch it or the clone(). In our case the scan().

**Comment by mdoussias** [comment]
So should I just remove the try-catch statement in clone()?
Sorry I'm just learning how clone() works.  
I'm reading again now and I'll go back over the spec.

**Comment by p12345vls** [comment]
Yes.

**Comment by p12345vls** [comment]
Sorry by accident I merged your second pull request. And now the first has conflict.

**Comment by mdoussias** [comment]
That's Ok, I canceled and put another pull request in.  Easier than resolving conflicts.


For clone() when I take the try-catch out, it shows red for errors.  I need to read more on this.

**Comment by mdoussias** [comment]
While I find out how to fix it, here is the code I had so far if anyone wants it....


   /**
    * Clone Method. Allows for BarcodeImage object to be cloned
    * 
    * @return clone of BarcodeImage object or returns null if exception
    */
   @Override
   public BarcodeImage clone()
   {
      try
      {
         return (BarcodeImage) super.clone();
      } catch (CloneNotSupportedException exception)
      {
         return null; // Returns null if cannot clone object
      }
   }

**Comment by p12345vls** [comment]
It is an easy fix. I will do it and and will update the DataMatrix file. The error will be gone.

**Comment by mdoussias** [comment]
Ok cool.  Thank you Pavlos.
Can I assign you to this one issue?

**Comment by p12345vls** [comment]
Sure
