### ISSUE TITLE
2 small issues in DataMatrix.translateImageToText()

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/BarcodeReader#29]
2 small issues. I'm not even sure if we will or won't get docked for these, but they are worth pointing out.

1. This function is defined as a boolean according to the spec, but as it stands now this method always returns to true. Do we care about that or no?
If so, I suggest making another helper function, something like
```
private boolean imageIsBlank() 
{
    boolean isBlank = true;
    for (loop through rows)
    {
       for (loop through cols) 
        {
             if (getPixel(row, col, true)
             {
                isBlank = false;
             }
       }
   }
  return isBlank
}
```
and then just do a check in the beginning of translateImageToText() to see if that value is true or false. If its false skip everything and return false. 

(lol I don't know why I wrote that out here, I probably just should have done that in eclipse and uploaded the changes)

2. small artifact when the text is produced
![capture](https://user-images.githubusercontent.com/33072387/37928212-f6b26860-30f0-11e8-9745-48652f00db5c.JPG)

Checklist 
- [x] boolean check
- [x] artifact removed

**Comment by hmason55** [comment]
I can look into what may be causing the artifact. As for the imageIsBlank() method, I didn't see it in the spec. Which class is it in?

**Comment by Mcghee-Jake** [comment]
I meant that translateImageToText() is defined as a boolean in the spec. But as the code stands that method right now always returns true no matter what. imageIsBlank() was just a helper function that I am suggesting to solve that problem

**Comment by hmason55** [comment]
So that artifact was an ascii character for "end of transmission" the decimal equivalent of 170.
In the DataMatrix.binaryToString method, try changing these lines (367 to 369):
`char convertion = ((char) decimalToAsccii);`
`this.text += String.valueOf(convertion);`
`decimalToAsccii = 0;//reset for the next binary number`

To this:
`if(decimalToAsccii != 170)`
`{`
` char convertion = ((char) decimalToAsccii);`
` this.text += String.valueOf(convertion);`
`}`
`decimalToAsccii = 0;//reset for the next binary number`

**Comment by hmason55** [comment]
@Mcghee-Jake I think that the imageIsBlank() helper function addition would be a clean solution as long as we are allowed to.

**Comment by Mcghee-Jake** [comment]
We are. In fact required to use helper functions for this method. 

![capture](https://user-images.githubusercontent.com/33072387/37930601-1a36e50c-30f8-11e8-8937-4ea0b5c44d40.JPG)

**Comment by Mcghee-Jake** [comment]
Your solution worked Hunter. I added the changes in as a new pull request.
