### ISSUE TITLE
DataMatrix

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/BarcodeReader#3]
This class is a pseudo Datamatrix data structure, not a true Datamatrix, because it does not contain any error correction or encoding.  However, it does have the 2D array format and a left and bottom BLACK "spine" as well as an alternating right and top BLACK-WHITE pattern as seen in the image.

Remember: **DataMatrix** implements **BarcodeIO**.

**Comment by Mcghee-Jake** [comment]
I'm down to handle this class, I'd like to step up big this week (and in module 6) because I will be out of town next weekend friday the 30th to sunday the 1st

**Comment by Mcghee-Jake** [comment]
Constructors
 - [x] DataMatrix()
 - [x]  DataMatrix(BarcodeImage image)
 - [x]  DataMatrix(String text)

 Other methods
 - [x] public int getActualWidth()
 - [x] public int getActualHeight() 
 - [x] private int computeSignalWidth();
 - [x] private int computeSignalHeight()
 - [x] private void cleanImage()

 BarcodeIO implementation
 - [x] public boolean scan(BarcodeImage bc)
 - [x] public boolean readText(String text)
  - [x] public boolean generateImageFromText()
  - [x] public boolean translateImageToText()
  - [x] public void displayTextToConsole()
  - [x] public void displayImageToConsole()

**Comment by hmason55** [comment]
@Mcghee-Jake Sounds great, I will try to be more involved this week as well. Next week we should have this down and be able to make it work.

**Comment by mdoussias** [comment]
Awesome.  This is a big class, so let me know if you need assistance.  
Also, we didn't leave anything for Pavlos.

**Comment by Mcghee-Jake** [comment]
Pavlos perhaps if you want you could help with some of these functions. Whatever your pick is. 

Is there a way github that we can assign ourselves tasks _within_ an issue? For example is there a way Pavlos or I could assign our names to the specific functions? 

If we open a new issue for each function it make things a bit necessary, but I would really like to have some way to assign ourselves to specific components _within_ a class.

**Comment by Mcghee-Jake** [comment]
Also we are going to still need someone to combine all the classes into one file, build the main() function, and format according to the spec. I'll open a new issue for that.

**Comment by mdoussias** [comment]
For assigning tasks you can just assign yourself to the task and then write a comment here for what you're working on.     But that is more organized but still a little sloppy.  
Just a thought we can also edit the Issue at the top.  Not sure what the best solution is.

**Comment by hmason55** [comment]
Yeah you can either make 2 issues and assign each one to a person, or you can keep it in one issue and assign both people. If you do the second option you would probably need to edit the issue description (first comment) and use something like check boxes for each member's section:
for example:

**Member 1 Tasks**
- [ ] task 1
- [ ] task 2
- [ ] task 3

**Member 2 Tasks**
- [ ] task 4
- [ ] task 5
- [ ] task 6

**Comment by mdoussias** [comment]
Sorry... Cat to blame for closing the issue temporarily.

**Comment by p12345vls** [comment]
Yes Jake I will help you, sorry for late reply.

**Comment by p12345vls** [comment]
I need some more time to read about the assignment. I was very busy.

**Comment by Mcghee-Jake** [comment]
Sounds good Pavlos, please communicate when you have read over the spec so I can give you an updated account of what needs to be finished for this class and we can delegate the work then

**Comment by p12345vls** [comment]
I see that you marked above the constructors and some methods:

 DataMatrix()
 DataMatrix(BarcodeImage image)
 DataMatrix(String text)

 public int getActualWidth()
 public int getActualHeight()
 private int computeSignalWidth();
 private int computeSignalHeight()

Are these the methods you will be working on?

**Comment by Mcghee-Jake** [comment]
Yes. I am marking these whenever I start working on a method. It doesn't necessarily mean I won't work on the unchecked methods in the future, it just indicates that work has started on this method. 

Basically if a function is NOT checked off that means it is fair game. 

Please do the same so that I am also not redoing any work you have in progress. So each time you start working on a method please check it off here first so that I know not to work on that one.

Note: I also just checked off cleanImage()

**Comment by p12345vls** [comment]
Ok I marked the rest.
BarcodeIO implementation

**Comment by Mcghee-Jake** [comment]
Ok. So just to confirm. 

You have started working on all of these methods?

public boolean scan(BarcodeImage bc)
 public boolean readText(String text)
 public boolean generateImageFromText()
 public boolean translateImageToText()
 public void displayTextToConsole()
 public void displayImageToConsole()

I would prefer if we leave each one blank until work is started on them, that way I know what I could be working on if work hasn't started on it yet. Does that make sense or should I elaborate?

**Comment by p12345vls** [comment]
Sure I start with the first one, **public boolean scan(BarcodeImage bc)** I unmark the rest.

**Comment by mdoussias** [comment]
If you need help here, I can assist.  Once we can put this together, it will be easier to bug test BarcodeImage class.

**Comment by p12345vls** [comment]
Jake, in order to continue with the rest of the methods it seems that we should upload what we have created so far.

**Comment by p12345vls** [comment]
Jake ,I just pulled updates and there are some errors in the code, some instance variables are not defined. You might uploaded an incomplete file?

**Comment by Mcghee-Jake** [comment]
Ok thanks for the heads up. I'll look into it

**Comment by mdoussias** [comment]
Let me know if you need help on this class.  I have limited time tomorrow.

**Comment by p12345vls** [comment]
It will be good if we can figure out why the height and width are not correct after the test in the DataMatrix class.

**Comment by mdoussias** [comment]
Hi Pavlos, I will check that out now.  It may be something slightly off in the constructor for **BarcodeImage(String[] array)**

**Comment by p12345vls** [comment]
Ok fixed, it was a small detail in computeSignalWidth and computeSignalHeight 
image.getPixel(i,0) instead of image.getPixel(0,i)

**Comment by Mcghee-Jake** [comment]
Ok fixed the syntax errors, there was a ton! I was using a different code editor and I had assumed it was checking syntax but I was dead wrong. Won't make that mistake again. 

I also just tried texting my methods against BarcodeImage and they aren't working as expected :/ Could be something in DataMatrix or something in BarcodeImage, not sure yet. I'll have to look into it more tomorrow. I plan on working on it tomorrow morning.

**Comment by mdoussias** [comment]
I just fixed BarcodeImage(str[]) constructor.... Not sure if that has anything

I kept making logic errors, but now the image goes down to the bottom left.
WARNING Still needs to check for out of bounds and null values... and I'll be adding that soon.

**Comment by Mcghee-Jake** [comment]
Damn it took me a while to debug cleanImage().

We still need to write 
public boolean generateImageFromText()
 public boolean translateImageToText()
 public void displayTextToConsole()
 public void displayImageToConsole()

generateImageFromText()
and
boolean translateImageToText()
are going to be pretty difficult. 

I have some homework for my other class due at 6pm today so I need to focus on that right now but I will help take care of whatever is left once I finish my other homework.

**Comment by p12345vls** [comment]
I continue with the **boolean translateImageToText()**

**Comment by mdoussias** [comment]
I don't have much time to work today,

But displayImageToConsoly() or displayTextToConsole() might have some similarities to the display() method I made for testing in the **BarcodeImage** class.

Just a heads up.  Not sure if will help.

**Comment by p12345vls** [comment]
translateImageToText() is ready. Tomorrow I have very limited time. I can contribute after 8pm, if necessary.

**Comment by Mcghee-Jake** [comment]
I'll work on generateImageFromText();

**Comment by Mcghee-Jake** [comment]
Pavlos, 
Is it alright if I rename binaryToDecimal to binaryToString?
Because of the name I initially thought this method translated the binary data into decimal numbers and it took me a minute to realize that this method actually converts the binary data into an ASCII string. I think it might be a little more clear to the rest of us and the professor if it were named binaryToString.
What do you think?

**Comment by p12345vls** [comment]
Yes, if it is confusing we you can change it.

**Comment by Mcghee-Jake** [comment]
I'm going to close this because this class is essentially complete
