### ISSUE TITLE
Unused variable in DataMatrix.translateImageToText() method

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/BarcodeReader#32]
String imageToBinary = "";
Is never used in the DataMatrix.translateImageToText() method.

**Comment by mdoussias** [comment]
I'm looking at it now and I think the local variable **imageToBinary** is superfluous and can be deleted.  But I'll let the maker of the function decide.  Looks like **char[][] c** took its place, in which case **c** may need a more descriptive name.

I don't want to erase just yet in case I'm just not seeing what it's intended for.

**Comment by p12345vls** [comment]
This variable called the **printDecodedImage(String imageToBinary)**, and displayed the image in zeros and ones, someone deleted the call to this function so now it is not used. It was not required in the assignment instructions but it was a good for debugging and to displayed the decoded image. The **char [][]c** can have another name, feel free to give one. As for the **imageToBinary** either should  call the  **printDecodedImage** or delete it. Its up to you guys.

**Comment by mdoussias** [comment]
I'll put a pull request to delete.

**Comment by p12345vls** [comment]
Dont forget to delete also  the printDecodedImage(String imageToBinary)

**Comment by mdoussias** [comment]
Noted.

**Comment by mdoussias** [comment]
/**
    * Looks at the internal image stored in the implementing class, and produces
    * a companion text string.
    */
   public boolean translateImageToText()
   {
      if (imageIsBlank()) // Image is blank
      {
         return false;
      } 
      else // image is not blank
      {
         int topRow = (BarcodeImage.MAX_HEIGHT - getActualHeight());

         // Holds a 2D array of char values representing image
         char[][] charImgArray = 
            new char[BarcodeImage.MAX_HEIGHT - 1][getActualWidth()];

         for (int row = 1; row < BarcodeImage.MAX_HEIGHT - 1; row++)
         {
            for (int col = 1; col < getActualWidth(); col++)
            {
               // If statement if reached the point after the empty space
               // (Note: remember the array is shifted down)
               **if (row > topRow)
               {**
                  // Begin to decode after the Closed Limitation Line and
                  // Open Borderline
                  if (image.getPixel(row, col))
                  {
                     charImgArray[row][col] = '1';
                  } 
                  else
                  {
                     charImgArray[row][col] = '0';
                  }
               }
            }
         }
         binaryToString(topRow, charImgArray);
         return true;
      }
   }

**Comment by mdoussias** [comment]
I put in a pull request.
There was an if statement I couldn't tell what it was used for as the statement had no brackets.
I added brackets, but @pavlosp1967 Pavlos, can you quickly check after the pull request and ensure I did this right?  Then this issue can be closed.  
I tested the function and it worked.  

**Below is the area in question that was missing that I added brackets to:**
             // If statement if reached the point after the empty space
               // (Note: remember the array is shifted down)
               **if (row > topRow)**

**Comment by p12345vls** [comment]
Mac, if you tested it then it is fine.

**Comment by mdoussias** [comment]
Cool.  I'll close this one out.
