### ISSUE TITLE
public void binaryToString(int topRow, char[][] c)

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/BarcodeReader#38]
Last issue I see for refactoring consideration.  Thoughts?

- [ ] This section of the code is a little confusing to me?
Why not just have c1 as a variable named charValue?  
I can't see why c1 has to be an array?
    char[] c1 = new char[getActualWidth()];
    c1[i] = (c[topRow + i][j]);

- [ ]  I think the argument c[][] char array should be renamed to charImgArray to be a little more clear.

   /**
    * Helper method for translateImageToText(). Loops through the decoded image and
    * transposes rows with columns. Each column will be converted to row that will
    * hold a binary number to be converted to a decimal number and finally to
    * asccii code
    * 
    * @param topRow
    *           the row number where the image is shifted
    * @param c
    *           the array that holds the binary numbers
    */
   public void binaryToString(int topRow, char[][] c)
   {
      int decimalToAsccii = 0; // holds the sum of the binaries
      text = ""; // Make sure text is blank

      for (int j = 1; j < getActualWidth(); j++)
      {
         for (int i = 1; i < getActualHeight() - 1; i++)
         {
            char[] c1 = new char[getActualWidth()];
            c1[i] = (c[topRow + i][j]);
            // if ones, multiply by the power of two
             if (c1[i] == '1')
            {
               decimalToAsccii += Math.pow(2, Math.abs(i - 8));
            }
         }
         if (decimalToAsccii != 170)
         {
            char convertion = ((char) decimalToAsccii);
            this.text += String.valueOf(convertion);
         }
         decimalToAsccii = 0;// reset for the next binary number
      }
   }

**Comment by hmason55** [comment]
> Why not just have c1 as a variable named charValue?
> I can't see why c1 has to be an array?

@mdoussias 
Basically this, I don't really see why c1 needs to be an array.
I tried this and it still worked the same I think:
`char c1 = (c[topRow + i][j]);`
            `// if ones, multiply by the power of two`
            `if (c1 == '1')`
           `{`
               `decimalToAsccii += Math.pow(2, Math.abs(i - 8));`
            `}`

I also agree that c1 should be changed to charValue since that seems more descriptive at a glance.

> I think the argument c[][] char array should be renamed to charImgArray to be a little more clear.

I was going to say even something like "imageCharacters" would work but I kinda like charImgArray better.

**Comment by Mcghee-Jake** [comment]
Thoughts Pavlos? This is your code so it would be good to get your input.

If someone is available to make those suggested changes into a pull request that would be good.

**Comment by p12345vls** [comment]
Fixed.

**Comment by p12345vls** [comment]
Fixed and updated Assignment4.txt
