### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by hmason55** [team-makeSmart/BarcodeReader#4]
Use the tool, Gliffy, to build a UML diagram. [Use this link for Gliffy .](https://go.gliffy.com/go/html5/launch)  Create an account and then export your diagram to PDF for submission.

You can view the progress [HERE](https://go.gliffy.com/go/share/s2s2eheqw1vh0q9agakt)

**Comment by hmason55** [comment]
I can handle the UML diagram, it probably won't take long to complete so I'll be able to work on another task if needed.

**Comment by mdoussias** [comment]
Hunter, you did a lot already what with uploading all this to github and getting a skeleton for the files.
If I have any stumbling blocks tomorrow when I start coding I may ask for your help.  

Hopefully you can help to refactor or clean my code if you see anything that can be done better.

**Comment by hmason55** [comment]
I'll be around, just drop me a message if you have any questions about the code.

**Comment by hmason55** [comment]
The UML diagram is started, you can check it out [here](https://go.gliffy.com/go/share/s2s2eheqw1vh0q9agakt) or use the link in the first comment for this issue.
I don't think there is much more for me to add right now but after the other classes are finished I will revise it to include any additional methods that may have been added.

**Comment by hmason55** [comment]
Updated diagram to include helper methods, testing methods are still omitted. Class attributes and methods are now sorted alphabetically.

**Comment by Mcghee-Jake** [comment]
Double check DataMatrix in the UML before we submit, I added some changes today that need to be reflected in the UML
- removed WHITE_CHAR & BLACK_CHAR
- added more helper methods

**Comment by hmason55** [comment]
**DataMatrix**
- [x] Moved constructors to be listed above methods
- [x] Removed WHITE_CHAR
- [x] Removed BLACK_CHAR
- [x] Added binaryToString(int, char[][])
- [x] Added fillBarcodeFromText()
- [x] Added generateBarcodeBorders()
- [x] Added imageIsBlank()
- [x] Added printDecodedImage(String imageToBinary)


**BarcodeImage**
- [x] Moved constructors to be listed above methods

**Comment by hmason55** [comment]
Do you think we need to include all the members of the Cloneable interface from java.lang.Cloneable?

**Comment by mdoussias** [comment]
@hmason55  I wouldn't think so, but wouldn't hurt to ask in course forum.  
Regarding including all members of Cloneable interface.

**Comment by mdoussias** [comment]
The UML looks good to me.... I'm getting sleepy so I'll check it one last time tomorrow about lunch....

**Comment by p12345vls** [comment]
We need to check any updates that have been made in the files so that the UML is compatible with the changes.

**Comment by mdoussias** [comment]
I put my last pull request....  So if that is accepted the UML diagram can be finalized and checked.
I checked it, but can someone else just quickly run the program and make sure it works.

**Comment by p12345vls** [comment]
We need a default constructor in BarcodeImage Class

**Comment by hmason55** [comment]
@p12345vls BarcodeImage has 2 constructors, does it need more? I think it matches the text file now.

**Comment by p12345vls** [comment]
It looks good to me
