### ISSUE TITLE
Convert into single file and main() function

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/BarcodeReader#8]
- [x] Convert into single file
- [x] Main() function according to spec
- [x] Final Formatting
- [x] Generate sample output
- [x] Remove tabs

**Comment by hmason55** [comment]
Also we should keep in mind that this should only be done after all the other classes are working and ready for turn in (including comments).

**Comment by mdoussias** [comment]
On comments.,,

In eclipse **ctrl-shift-f** auto-formats everything beautiful if you setup eclipse according to professors instructions.

**Comment by hmason55** [comment]
Additional changes:

**DataMatrix**
- [x] Removed testing helper method printDecodedImage(String imageToBinary)

**BarcodeImage**
- [x] Removed testing method testImage()
- [x] Removed testing method displayToConsole()
